version: '3.8'
services:
  gobong-db:
    container_name: gobong-db
    build:
      dockerfile: Dockerfile
      context: ./db
    image: seunggison/gobong-database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"