spring:
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/gobong
    username: root
    password: ${spring.datasource.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace


jwt:
  secret: ${jwt.secret}
  token-validity-time: ${jwt.token-validity-time}
  issuer: ${jwt.issuer}
