spring:
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/gobong
    username: root
    password: ${spring.datasource.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth2.client.registration.google.client-id}
            client-secret: ${oauth2.client.registration.google.client-secret}
            client-name: google
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

          naver:
            client-id: ${oauth2.client.registration.naver.client-id}
            client-secret: ${oauth2.client.registration.naver.client-secret}
            client-name: naver
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace


jwt:
  secret: ${jwt.secret}
  token-validity-time: ${jwt.token-validity-time}
  issuer: ${jwt.issuer}
